name: tests
on: 
  pull_request:
jobs:
  test: #Job responsável por compilar os testes e gerar os artefatos relacionados
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Build tests
        run: |
          pytest flask_backend/tests --junitxml=test/test.xml
     
      - name: Show results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() #Sempre executa essa etapa
        with:
          files: test/test.xml #Arquivo com os resultados dos testes
